version: '3'

services:
  d04:
    container_name: d04
    build:
      context: docker
      args:
        USER: ${USER}
    environment:
      USER: ${USER}
    volumes:
      - ./:/var/www/d04/
    ports:
      - 8383:80
